### ISSUE TITLE
Variables on stack limit?

### ISSUE THREAD

**Issue by akubiczek** [irmen/prog8#21]
Hello again :)

Is there any limit of variables I can declare? 

Look at this code snippet:

```
-target cx16

        ubyte i
        for i in 0 to BOARD_FIELDS - 1 {

            if (board_fields[i-5] == 4) {
                txt.plot(30, 12)
            }   
```

It compiles to:

```
 ;if (board_fields[i-5] == 4) starts here:
        lda  i
	sta  prog8_autovar_index_1835841364
	sec
	sbc  #5
	sta  prog8_autovar_index_1835841364
	ldy  prog8_autovar_index_1835841364
	lda  board_fields,y

;this is important:
	sta  P8ESTACK_LO,x
	dex
	lda  #4
	sta  P8ESTACK_LO,x
	dex
	jsr  prog8_lib.equal_b ;this comparison sometimes fails
	inx
	lda  P8ESTACK_LO,x
	beq  _prog8_label_51_if_end 
	ldy  #$1e
	lda  #12
	jsr  txt.plot
```

It works for a while until it stops working :) The problem is with _prog8_lib.equal_b_ procedure and X-register. I have debugged code and found that X-register is equal to $00 what causes problem:

```
;X = $00
;this is important:
    sta $0400,x 
    dex ;X = $ff
    lda #04
    sta $0400,x
    dex ;X = $fe
    jsr prog8_lib.equal_b
    inx
    lda $0400,x
    beq _prog8_label_51_if_end


prog8_lib.equal_b:
    lda $0402,x ;X = $fe, $402+$FE=$500 WRONG!
    cmp $0401,x 
```

So it should compare $0400 to $04ff - instead it compares $0500 ($402+$FE) to $04ff ($401+$fe).

I found a solution, I can change:

`if (board_fields[i-5] == 4) {`

into:

```
ubyte val = board_fields[i-5]
if (val == 4) {
```

And it's even faster because it doesn't use _prog8_lib.equal_b_ anymore but I would like to know why the problem exists in my original case.

**Comment by akubiczek** [comment]
Update:

Anyway, I've found that complex *if* conditions it's safer to write as nesting simple conditions. Example below makes troubles:

```
-target cx16

    if (i >= 10 and val1 == val4 and val2 == EMPTY_FIELD and val3 == val5) {
```

Nesting works well:

```
            if (i >= 10){
                if (val1 == val4) {
                    if (val2 == EMPTY_FIELD) {
                        if (val3 == val5) {
                            ;do sth
                        }
                    }
                }
            }
```

**Comment by irmen** [comment]
Maybe you found a stack corruption bug where the X register isn't properly inc/dec'd . Sometimes I made a mistake with this...
I'll have to investigate .

In the meantime, you could use the test_stack library module to print the X and SP registers on the screen to maybe see an anomaly?  (these should remain constant if the test() call is done always at the start of your program's game loop for instance)
Perhaps if you want to help even further, can you isolate the problematic code in a minimal test program that exposes the bug (if it's a bug).    I will have to have some code to compile to be able to reproduce this....

By the way, just as the cpu's hardware stack, the evaluation stack has a limit of 255 variables (bytes and words).  Unless you're doing very heavily nested evaluations it should be very hard to hit this limit....  That's why I suspect a stack corruption bug in the generated code.

**Comment by akubiczek** [comment]
No, I'm not touching any register on my self. Thank you, I'll investigate it further and let you know what I found. Unfortunately, even with changes I shown above the problem still exists - it just happens later.

**Comment by irmen** [comment]
yeah that sounds like an eval stack pointer bug then.

By the way have you tried with prog8 5.1?  (or even better yet, the in-development version from the master branch).... maybe the bug is already fixed

**Comment by akubiczek** [comment]
Hmmm, 5.1 version seems to work perfectly 👍

**Comment by irmen** [comment]
Well, that is great news!!
Seems like one of the fixes I made already solved the issue you ran into.

I'm closing this bug report for now, don't hesitate to re-open or make a new issue if you find something else.    I appreciate you taking the time and hope you enjoy prog8 :)
