### ISSUE TITLE
Using constants in assembler?

### ISSUE THREAD

**Issue by akubiczek** [irmen/prog8#22]
Hello :)

I got a short question today: can I use my own constants in an assembler code? I can see you use it in your libraries, for example in syslib.p8:

```
asmsub init_system()  {
    %asm {{
        lda  #$80
        sta  VERA_CTRL
```

However, when I try to use my constant, i.e:

```
    const ubyte SCREEN_BACKGROUND_COLOR = 1
    asmsub set_pallete_color(ubyte color @ A) {
        %asm {{
            lda #SCREEN_BACKGROUND_COLOR
```

it fails on assembling phase since the constant's name isn't replaced by value nor there is SCREEN_BACKGROUND_COLOR defined in *.asm file.

**Comment by irmen** [comment]
Interesting question!

Indeed, you cannot use constants declared in your code like that.  This is because Prog8 does _const-folding_. That means it replaces expressions with their resulting constant numbers if it can at compile time, to avoid generating needless assembly code for it.
Unfortunately this also means at this time, that the defined constants are simply lost in the resulting program (because they are fully removed from the program's syntax tree).

The reason you can use VERA_CTRL in assembler code is because it isn't defined as a const, but as a memory-mapped variable:
`&ubyte  VERA_CTRL         = VERA_BASE + $0005`

This is not applicable to your SCREEN_BACKGROUND_COLOR though. 

I'll think about perhaps dumping the prog8 constant definitions into the resulting assembly file......

In the meantime you could perhaps simply define the constant in your embedded assembly instead.  However this means you can no longer refer to it in your prog8 code, ofcourse....

**Comment by akubiczek** [comment]
OK, then again it's not clear to me why the compiler doesn't replace constants in assembly code at compile time. Prog8 passes assembler code as it is perhaps? Anyway, it is not a critical issue, it still could be addressed in future.

**Comment by irmen** [comment]
@akubiczek your observation is correct!   The in-line assembly is pasted verbatim into the resulting assembler file that the compiler generates. 
I'll make this more obvious in the manual.

**Comment by irmen** [comment]
To be clear for future readers of this: it currently _is_ possible to use constants defined in prog8 code by their name in assembly blocks as well, because they're included into the assembly output file.
