### ISSUE TITLE
Weird type error when casting const

### ISSUE THREAD

**Issue by cyborgar** [irmen/prog8#72]
I encountered this rather specific compile error when using something like this

```
const ubyte TEST = 10
byte x = TEST as byte + 1
```
which give

`ERROR initialisation value has incompatible type (UBYTE) for the variable (BYTE)`

Note that 

`byte x = 1 + TEST as byte`

works fine.

[test.txt](https://github.com/irmen/prog8/files/7454133/test.txt)

**Comment by irmen** [comment]
Interesting... :)
in the 7.2 branch I'm developing some changes to the way variable initialization expressions are handled, and this particular error no longer occurs there.
I'm still curious as to what caused it earlier, so will investigate a bit in the 7.1 version.  Seems like the type inference routine makes the wrong conclusion somehow

**Comment by irmen** [comment]
The first expression is parsed into:

`Typecast(IdentifierRef([TEST]) as BYTE) + NumericLiteral(UBYTE:1)`

while the second is parsed into:

`Typecast([NumericLiteral(UBYTE:1) + IdentifierRef([TEST])] as BYTE`

So yeah this makes sense now. The second casts the addition subexpression to BYTE while the first one first casts TEST into a BYTE and then adding an UBYTE constant to it.
Adding UBYTE to BYTE results in UBYTE which is not the same type as the variable, hence the error.

Additional observation:

    byte xx
    xx = TEST as byte + 1

Also works as expected. (incidentally, this is now how the current 7.2 branch treats the code above).
This works because there's a step in the compiler that does some silent typecasting for convenience sake, but _it doesn't seem to do so for variable initializer expressions._    
I'll see if this can/needs to be fixed.

**Comment by cyborgar** [comment]
I also saw that this didn't occur if the declaration occured separately. I'm using the first alternative already so if this is fixed for 7.2 there is no real reason to spend more time on this for my sake. Feel free to close.

**Comment by irmen** [comment]
Ok great!  But I'll leave this open for the small chance that the 7.2 changes need to be modified again. When I'm confident that they can remain as is (or perhaps when 7.2 is released) we can close this.

**Comment by irmen** [comment]
Actually, adding a unit test for this issue made me discover a corner case that actually crashes the compiler:

        const ubyte TEST = 10
        ubyte y1
        y1 = TEST + 1 as byte

It crashes with some internal syntax tree parent referencing error.

I fixed this in 7.2.
